// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./../components/A.vue')['default']
    B: typeof import('./../components/B.vue')['default']
    I18nTest: typeof import('./../components/i18nTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreTest: typeof import('./../components/storeTest.vue')['default']
  }
}
